---
#https://serverfault.com/questions/638507/how-to-access-host-variable-of-a-different-host-with-ansible
- name: Gather facts from reddit-db
  hosts: db
  tasks: []

- name: Configure App
  hosts: app
  become: true

  vars:
    db_host: "{{ hostvars['reddit-db']['ansible_default_ipv4']['address'] }}"

  roles:
    - app
