dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: joPsYC+rWSv+dQbiLfMpKUHDREq6WAx+XetO6lUZ9RsAQZhj2X+isJJTmj+kTXRY7PM1YVBCL+U67efeK4FOdkfw13J9KBCYVa5m5yvFfI20lz78nNMalYGtDmm8Uob5WeRfmmQPtQrqP4F2DerJjYZ8HAOGjuyrErFuWmYQaBVY/FSrUa8E8ErR3MC8OmGP4foVg4kb5aZSGMH9TLu4nQFVr2vg48Jb6JJY+dGJJ6mxfg2rJjuRDWnzadE6kIpXI4y/iVGzDcLZVQTRM/r+ISSWH3hIclbLGwQbazz/I48+tXOZ5mR99TtKJm2FgspaDgg6wQs4qZSuSiIDYruYbN3hsZllxdLqTzzEa5J4U3J612DftQb2LyVRdyH0n87HiqjvGNHpEUGgan6o9T/qFZiOQQIRJKBwgoOicxXYKyQ1325McYg74G0tIA4ocDUAJ5OjlUfn87AW0BZnvsTJUKIeVtgfJv5ryUxYRVXmWNXZGF+tzua+KHzTsHvCTSZm0hHah/Sz0F8d1RHoLYm9ghyntnKWIzT+aczlgtMuaXCYi1eUtGLWRkSAEUbtPVMuduKMAKo1NUZltdpfVxCgHHRB/uHSlPkgpA0iYNUyDtvFp2206D18UmS+LNfu2RujyMIf4ATrSbyWxp4dzyA3U6b8yy8j5pCKRkWQ20Z16ao=
